List.destroy_all
ActiveRecord::Base.connection.reset_pk_sequence!('lists')


i = 1
while i < 13 do 
    List.create(number: i, title: "#{i}")
    i+=1
end 

#creating categories for the 12 lists
#list 1
Category.create(name: "A Boy's Name", list_id: 1)
Category.create(name: "A River", list_id: 1)
Category.create(name: "An Animal", list_id: 1)
Category.create(name: "Things That Are Cold", list_id: 1)
Category.create(name: "Insects", list_id: 1)
Category.create(name: "TV Show", list_id: 1)
Category.create(name: "Things That Grow", list_id: 1)
Category.create(name: "Fruits", list_id: 1)
Category.create(name: "Things That Are Black", list_id: 1)
Category.create(name: "School Subject", list_id: 1)
Category.create(name: "Movie Title", list_id: 1)
Category.create(name: "Musical Instrument", list_id: 1)

#list 2
Category.create(name: "Authors", list_id: 2)
Category.create(name: "Bodies of Water", list_id: 2)
Category.create(name: "Species of Bird", list_id: 2)
Category.create(name: "Countries", list_id: 2)
Category.create(name: "Cartoon Characters", list_id: 2)
Category.create(name: "Holidays", list_id: 2)
Category.create(name: "Things That Are Cold", list_id: 2)
Category.create(name: "Sports Team", list_id: 2)
Category.create(name: "Articles of Clothing", list_id: 2)
Category.create(name: "Name of a Relative", list_id: 2)
Category.create(name: "Games", list_id: 2)
Category.create(name: "Famous Athletes", list_id: 2)

#list 3
Category.create(name: "School Supplies", list_id: 3)
Category.create(name: "Things That Are Hot", list_id: 3)
Category.create(name: "Heroes", list_id: 3)
Category.create(name: "Girl's Names", list_id: 3)
Category.create(name: "Fears/Phobias", list_id: 3)
Category.create(name: "Television Stars", list_id: 3)
Category.create(name: "Colors", list_id: 3)
Category.create(name: "Species of Fish", list_id: 3)
Category.create(name: "Things That You Plant", list_id: 3)
Category.create(name: "States", list_id: 3)
Category.create(name: "Sports Equipment", list_id: 3)
Category.create(name: "Tools", list_id: 3)

#list 4
Category.create(name: "Breakfast Foods", list_id: 4)
Category.create(name: "Gifts", list_id: 4)
Category.create(name: "Flowers", list_id: 4)
Category.create(name: "Ice Cream Flavors", list_id: 4)
Category.create(name: "A Drink", list_id: 4)
Category.create(name: "Toys", list_id: 4)
Category.create(name: "Cities", list_id: 4)
Category.create(name: "Things in the Kitchen", list_id: 4)
Category.create(name: "Found in the Ocean", list_id: 4)
Category.create(name: "Nicknames", list_id: 4)
Category.create(name: "Hobbies", list_id: 4)
Category.create(name: "Parts of the Body", list_id: 4)

#list 5
Category.create(name: "Sandwiches", list_id: 5)
Category.create(name: "Items in a Catalog", list_id: 5)
Category.create(name: "World Leaders / Politicians", list_id: 5)
Category.create(name: "School Subjects", list_id: 5)
Category.create(name: "Excuses for Being Late", list_id: 5)
Category.create(name: "Ice Cream Flavors", list_id: 5)
Category.create(name: "Things That Jump or Bounce", list_id: 5)
Category.create(name: "Things That Can Kill You", list_id: 5)
Category.create(name: "Things in a Park", list_id: 5)
Category.create(name: "Foreign Cities", list_id: 5)
Category.create(name: "Stones/Gems", list_id: 5)
Category.create(name: "Musical Instruments", list_id: 5)

#list 6
Category.create(name: "Nicknames", list_id: 6)
Category.create(name: "Things in the Sky", list_id: 6)
Category.create(name: "Pizza Toppings", list_id: 6)
Category.create(name: "Colleges / Universities", list_id: 6)
Category.create(name: "Wines", list_id: 6)
Category.create(name: "Countries", list_id: 6)
Category.create(name: "Things That Have Spots", list_id: 6)
Category.create(name: "Historical Figures", list_id: 6)
Category.create(name: "Fears / Phobias", list_id: 6)
Category.create(name: "Terms of Endearment", list_id: 6)
Category.create(name: "Items in This Room", list_id: 6)
Category.create(name: "Drugs", list_id: 6)

#list 7
Category.create(name: "Fictional Characters", list_id: 7)
Category.create(name: "Menu Items", list_id: 7)
Category.create(name: "Magazines", list_id: 7)
Category.create(name: "Capitals", list_id: 7)
Category.create(name: "Kinds of Candy", list_id: 7)
Category.create(name: "Items You Save Up to Buy", list_id: 7)
Category.create(name: "Footware", list_id: 7)
Category.create(name: "Things You Keep Hidden", list_id: 7)
Category.create(name: "Items in a Suitcase", list_id: 7)
Category.create(name: "Things With Tails", list_id: 7)
Category.create(name: "Sports Equipment", list_id: 7)
Category.create(name: "Crimes", list_id: 7)

#list 8
Category.create(name: "Things That Are Sticky", list_id: 8)
Category.create(name: "Awards/Ceremonies", list_id: 8)
Category.create(name: "Cars", list_id: 8)
Category.create(name: "Herbs/Spices", list_id: 8)
Category.create(name: "Bad Habits", list_id: 8)
Category.create(name: "Cosmetics/Toiletries", list_id: 8)
Category.create(name: "Celebrities", list_id: 8)
Category.create(name: "Cooking Utensils", list_id: 8)
Category.create(name: "Reptiles/Amphibians", list_id: 8)
Category.create(name: "Parks", list_id: 8)
Category.create(name: "Leisure Activities", list_id: 8)
Category.create(name: "Things You're Allergic To", list_id: 8)

#list 9
Category.create(name: "Restaurants", list_id: 9)
Category.create(name: "Notorius People", list_id: 9)
Category.create(name: "Tourist Attractions", list_id: 9)
Category.create(name: "Things in a Medicine Cabinet", list_id: 9)
Category.create(name: "Toys", list_id: 9)
Category.create(name: "Household Chores", list_id: 9)
Category.create(name: "Bodies of Water", list_id: 9)
Category.create(name: "Authors", list_id: 9)
Category.create(name: "Halloween Costumes", list_id: 9)
Category.create(name: "Weapons", list_id: 9)
Category.create(name: "Things That Are Round", list_id: 9)
Category.create(name: "Words Associated With Exercise", list_id: 9)

#list 10
Category.create(name: "Sports", list_id: 10)
Category.create(name: "Song Titles", list_id: 10)
Category.create(name: "Parts of the Body", list_id: 10)
Category.create(name: "Ethnic Foods", list_id: 10)
Category.create(name: "Things You Shout", list_id: 10)
Category.create(name: "Foreign Language Words", list_id: 10)
Category.create(name: "Girl's Names", list_id: 10)
Category.create(name: "Ways to Get From Here to There", list_id: 10)
Category.create(name: "Items in a Kitchen", list_id: 10)
Category.create(name: "Villains", list_id: 10)
Category.create(name: "Flowers", list_id: 10)
Category.create(name: "Things You Replace", list_id: 10)

#list 11
Category.create(name: "Baby Foods", list_id: 11)
Category.create(name: "Famous Duos and Trios", list_id: 11)
Category.create(name: "Things Found in a Desk", list_id: 11)
Category.create(name: "Vacation Spots", list_id: 11)
Category.create(name: "Diseases", list_id: 11)
Category.create(name: "Words Associated With Money", list_id: 11)
Category.create(name: "Items in a Vending Machine", list_id: 11)
Category.create(name: "Movie Titles", list_id: 11)
Category.create(name: "Games", list_id: 11)
Category.create(name: "Things You Make", list_id: 11)
Category.create(name: "Beers", list_id: 11)
Category.create(name: "Things at a Circus", list_id: 11)

#list 12
Category.create(name: "Vegetables", list_id: 12)
Category.create(name: "Historic Events", list_id: 12)
Category.create(name: "Things You Throw Away", list_id: 12)
Category.create(name: "Occupations", list_id: 12)
Category.create(name: "Appliances", list_id: 12)
Category.create(name: "Acronyms", list_id: 12)
Category.create(name: "Drinks", list_id: 12)
Category.create(name: "Musical Groups", list_id: 12)
Category.create(name: "Store Names", list_id: 12)
Category.create(name: "Things at a Football Game", list_id: 12)
Category.create(name: "Trees", list_id: 12)
Category.create(name: "Personality Traits", list_id: 12)